# Site settings
title: 'val y = f(x)'
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Writing about software development
baseurl: ""
#twitter_username: jekyllrb
url: "http://valydia.github.io" # the base hostname & protocol for your site
github_username:  valydia

# Build settings
markdown: kramdown
